### ISSUE TITLE
gmail compatible 

### ISSUE THREAD

**Issue by rokopi-byte** [Schmandre/notifyTVIDChange#1]
Hi,
First of all thank you for your work! I've run into this annoying situation where teamviewer changed ID!
I've tested your repo and only made this change to make it work with a gmail account as a sender.
In mail.py just change this:

```
server = smtplib.SMTP(config.smtpServer, config.smtpServerPort)
server.starttls()
```

into this:

```
server = smtplib.SMTP_SSL(config.smtpServer, config.smtpServerPort)
server.ehlo() 
```

Also be sure to enable "less secure apps" in the google account settings. 
In my case I had to also to run the script as root.

**Comment by Schmandre** [comment]
Thank you for your feedback ;) just changed it 👍
